//
//  Tests.h
//  VexFlow
//
//  Created by Scott Riccardelli on 1/1/15
//  Copyright (c) 2015 feedbacksoftware.com. All rights reserved.
//

#ifndef VexFlow_Tests_h
#define VexFlow_Tests_h

#import "AccidentalTests.h"
#import "AnimationTests.h"
#import "AnnotationTests.h"
#import "ArticulationTests.h"
#import "AutoBeamFormattingTests.h"
#import "BeamTests.h"
#import "BendTests.h"
#import "BoundingBoxTests.h"
#import "ChordTest.h"
#import "ClefTests.h"
#import "CurveTests.h"
#import "DotTests.h"
#import "FormatterTests.h"
#import "GraceNoteTests.h"
#import "KeyClefTests.h"
#import "KeyManagerTests.h"
#import "KeySignatureTests.h"
#import "LayerNoteTests.h"
#import "Mocks.h"
#import "ModifierTests.h"
#import "MusicTests.h"
#import "NodeTests.h"
#import "NoteHeadTests.h"
#import "NotationsGridTests.h"
#import "NotationsGridClassicTests.h"
#import "NotationsCollectionTests.h"
#import "OrnamentTests.h"
#import "ParserTests.h"
#import "PedalMarkingTests.h"
#import "PercussionTests.h"
#import "PlayNoteTests.h"
#import "RefreshAnimationTest.h"
#import "RestsTest.h"
#import "RhythmTests.h"
#import "ScrollViewTests.h"
#import "StaffTests.h"
#import "StaffConnectorTests.h"
#import "StaffHairpinTests.h"
#import "StaffLineTests.h"
#import "StaffModifierTests.h"
#import "StaffNoteTests.h"
#import "StaffTieTests.h"
#import "StringNumberTests.h"
#import "StrokesTests.h"
#import "TableTests.h"
#import "TabNoteTests.h"
#import "TabSlideTests.h"
#import "TabStaffTests.h"
#import "TabTieTests.h"
#import "TextBracketTests.h"
#import "TextNoteTests.h"
#import "TextTests.h"
#import "ThreeVoiceTests.h"
#import "TickContextTests.h"
#import "TimeSignatureTests.h"
#import "TransformTests.h"
#import "TuningTests.h"
#import "TupletTests.h"
//#import "VexFlowTestHelpers.h"
#import "VibratoTests.h"
#import "VoiceTests.h"

#endif
