//
//  TestType2.h
//  VexFlow
//
//  Created by Scott on 6/6/15.
//  Copyright (c) 2015 feedbacksoftware.com. All rights reserved.
//

#import <Foundation/Foundation.h>

// clang-format off
REFLECTABLE_ENUM(NSInteger, TestType,
    NoneTestType,
    AccidentalTestType,
    AnimationTestType,
    AnnotationTestType,
    ArticulationTestType,
    AutoBeamFormattingTestType,
    BeamTestType,
    BendTestType,
    BoundingBoxTestType,
    ClefTestType,
    CurveTestType,
    DotTestType,
    EveryThingTestType,
    FormatterTestType,
    GraceNoteTestType,
    InfiniteScrollTestType,
    KeyClefTestType,
    KeyManagerTestType,
    KeySignatureTestType,
    LayerNoteTestsTestType,
    MocksType,
    ModifierTestType,
    MusicTestType,
    NodeTestType,
    NoteHeadTestType,
    NotationsGridClassicTestType,
    NotationsCollectionTestsType,
    NotationsGridTestType,
    OrnamentTestType,
    ParseTestType,
    PedalMarkingTestType,
    PercussionTestType,
    PlayNoteTestType,
    RefreshAnimationTestType,
    RestsTestType,
    RhythmTestType,
    ScrollViewTestType,
    StaffTestType,
    StaffConnectorTestType,
    StaffHairpinTestType,
    StaffLineTestType,
    StaffModifierTestType,
    StaffNoteTestType,
    StaffTieTestType,
    StringNumberTestType,
    StrokesTestType,
    TableTestType,
    TabNoteTestType,
    TabSlideTestType,
    TabStaffTestType,
    TabTieTestType,
    TextBracketTestType,
    TextNoteTestType,
    TextTestType,
    ThreeVoiceTestType,
    TickContextTestType,
    TimeSignatureTestType,
    TransformTestType,
    TuningTestType,
    TupletTestType,
    VibratoTestType,
    VoiceTestType,
);
// clang-format on